### ISSUE TITLE
Type macros are not supported

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro-hack#10]
https://github.com/rust-lang/rfcs/blob/master/text/0873-type-macros.md

Rust macro_rules macros can be expanded in type position:

```rust
macro_rules! t {
    () => { u32 }
}

fn main() {
    let _: t!() = 0;
}
```

This is not possible with proc-macro-hack.

**Comment by CreepySkeleton** [comment]
proc-macros in type context are [stable starting from 1.40](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html). The issue is fixed

**Comment by dtolnay** [comment]
:+1:
