### ISSUE TITLE
Expression macro cannot be used as enum discriminant

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro-hack#11]
```rust
#[macro_use]
extern crate demo_hack;

pub enum E {
    A = add_one!(1)
}
```

https://github.com/rust-lang/rust/issues/40350

**Comment by Mark-Simulacrum** [comment]
This has been fixed in Rust master, just so you know; I don't know if any changes here need to be made.

**Comment by dtolnay** [comment]
Thank you! I will close the issue when I confirm it is fixed in a nightly.
