### ISSUE TITLE
Item macro inside impl block

### ISSUE THREAD

**Issue by pravic** [dtolnay/proc-macro-hack#18]
It looks like that is not possible.

Since `two_fn!(two)` expands to

```rust
// two_fn!(two);

#[allow(unused)]
enum ProcMacroHack { Input = ("two", 0).1, }
fn two() -> u8 { 2 }
```

we can't put it inside an `impl` block:
> error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `enum`

```rust
struct One;
impl One {
  two_fn!(two);
}
```

**Comment by dtolnay** [comment]
Thanks! I added this to the list of limitations in the readme.

**Comment by dtolnay** [comment]
Proc macros in impl blocks are stable as of Rust 1.30 so this is no longer a proc-macro-hack issue.
