### ISSUE TITLE
Provide access to $crate in the macro impl

### ISSUE THREAD

**Issue by carllerche** [dtolnay/proc-macro-hack#19]
I'm not sure this is possible, but it is a follow up from our talk on IRC.

I'm wondering if it would be possible for the `decl` macro to include `$crate` in the `enum ProcMacroHack`.

This would help dealing with cases where the caller renames the `extern crate` that has the macro def.

**Comment by dtolnay** [comment]
I tried this and it seems to work as I would expect on Rust 1.24 (but not earlier versions) edad1802c480d00b58fb862fffd871a82a3916cb. I will try to see if we can provide an implementation that would work on older compilers.

**Comment by dtolnay** [comment]
Here is a sketchy modification that seems to make it work on any version of Rust. 1e152786f81b03b3ea9f0c7c51a28006e7e05ea8

**Comment by dtolnay** [comment]
The sketchy way works for expression macros but not item macros. I would be okay making that change. @carllerche for your use case do you need this to work in item macros? I think that may be more complicated.

**Comment by dtolnay** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/62325.
