### ISSUE TITLE
Use a proc macro in its own crate

### ISSUE THREAD

**Issue by Michael-F-Bryan** [dtolnay/proc-macro-hack#24]
I'm going back over my [include_dir] crate and converting it to use a proc macro and one thing I'd like to do is include the source for `include_dir` inside itself as an example. Similar to [error chain's generated example][ec].

Do you know if there's a way to call a `proc_macro_hack` macro from within the declaration crate without getting name resolution errors? At the moment I'm getting ambiguous naming issues because the crate name and macro name are the same, and deeper down I create a `::include_dir::Dir`. 

```rust
// include_dir/src/lib.rs
pub static INCLUDE_DIR_SRC: Dir = include_dir!("./src");
```

expands roughly to the following, according to `cargo expand`:

```rust
pub static INCLUDE_DIR_SRC: Dir = ::include_dir::Dir {
    path: "",
    files: &[
        ::include_dir::File {
            path: "dir.rs",
            contents: &[ ... ],
        },
        ::include_dir::File {
            path: "file.rs",
            contents: &[ ... ],
        },
        ::include_dir::File {
            path: "globs.rs",
            contents: &[ ... ],
        },
        ::include_dir::File {
            path: "lib.rs",
            contents: &[ ... ],
        },
    ],
    dirs: &[],
}
```

But then after macro expansion it tries to resolve the `::include_dir::Dir` type and we get this error:

```text
error[E0223]: ambiguous associated type
  --> include_dir\src\lib.rs:65:14
   |
65 |     #[derive(include_dir_impl)]
   |              ^^^^^^^^^^^^^^^^ ambiguous associated type
...
70 |     proc_macro_call!()
   |     ------------------ in this macro invocation
   |
   = note: specify the type using the syntax `<include_dir as Trait>::Dir`
```

([source code](https://github.com/Michael-F-Bryan/include_dir/tree/ace95bb557d75c9f2bbb3ab70127047d1fd93c9a))

[ec]: https://docs.rs/error-chain/0.11.0/error_chain/example_generated/index.html

**Comment by dtolnay** [comment]
Here is how Diesel solves the same problem:

- https://github.com/diesel-rs/diesel/blob/v1.3.0/diesel/src/macros/mod.rs#L1138-L1145
- https://github.com/diesel-rs/diesel/commit/3d4613d22ec60d08cd9a9cdb2241511436f36c6c

The generated code needs to invoke a macro_rules macro that uses $crate to bring the right things into scope.

**Comment by Michael-F-Bryan** [comment]
Thanks a lot @dtolnay, that worked perfectly!

For people visiting this thread at some point in the future, [here is a diff][1] showing what I needed to do to make it work.

[1]: https://github.com/Michael-F-Bryan/include_dir/commit/66699724873f8484f5bb3111d1dad2c7aac8caf5
