### ISSUE TITLE
`use proc_macro::...` -> `use crate::proc_macro::...` in examples?

### ISSUE THREAD

**Issue by anp** [dtolnay/proc-macro-hack#27]
In a 2018 edition crate, the recent module system changes prevent the current README example from working on a recent nightly. Referencing the `proc_macro` crate as `crate::proc_macro` appears to resolve the problem for me. Is this the correct fix?

**Comment by dtolnay** [comment]
Yes, I would use `crate::proc_macro::` until we land the stabilization (and possibly backport) for https://github.com/rust-lang/rust/issues/55599. Let's update the documentation to use 2018 edition as soon as the edition is officially released.

**Comment by dtolnay** [comment]
Updated example code to 2018 edition in 87f72917ddabadb12fb1eb614559e07dc91dfb23.
