### ISSUE TITLE
Is it possible to eagerly expand macros contained in input?

### ISSUE THREAD

**Issue by golddranks** [dtolnay/proc-macro-hack#3]
I guess not, since crates like `diesel` support syntaxes like `infer_schema!("dotenv:DATABASE_URL");` instead of `infer_schema!(dotenv!("DATABASE_URL"));`, but I had to ask :D

**Comment by dtolnay** [comment]
As far as I know, there is no way. Here is an RFC for it: https://github.com/rust-lang/rfcs/pull/1628.
