### ISSUE TITLE
Passing $crate from macro_rules fails

### ISSUE THREAD

**Issue by Ralith** [dtolnay/proc-macro-hack#34]
Reproduce by running `cargo test` in [this testcase](https://github.com/dtolnay/proc-macro-hack/files/3351775/testcase.tar.gz).

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to fix this.

**Comment by dtolnay** [comment]
We need to find the step where the $crate token decomposes from `Ident { ident: "$crate" }` (which is how rustc is supposed to treat it) to `Punct { ch: '$', spacing: Alone }, Ident { ident: "crate" }`.

**Comment by dtolnay** [comment]
Look like a compiler bug -- closing in favor of https://github.com/rust-lang/rust/issues/62325.

**Comment by Ralith** [comment]
Thanks for investigating!
