### ISSUE TITLE
`#[proc_macro_hack]` reexport cannot handle leading `::` in path

### ISSUE THREAD

**Issue by danielhenrymantilla** [dtolnay/proc-macro-hack#36]
As we can see from [the code](https://github.com/dtolnay/proc-macro-hack/blob/ca8854bc92b2621748b8031d327e7208bcd792e8/src/lib.rs#L189), when using the `#[proc_macro_hack]` attribute to "decorate" a reexport (_i.e._, in the "declaration crate"), it expects to start parsing

```rust
use $implementation_crate_name:ident ::
```

However, given that we are reexporting from a crate, a way to do this in the 2018 edition (the cleanest way imho, since it avoids any potential path ambiguity), would be to use a leading pair of colons:

```rust
#[proc_macro_hack]
use ::implementation_crate_name::proc_macro_name;
```

That's why it would be great if `proc_macro_hack` in reexport position was changed so that it expects to start parsing

```rust
use $(::)? $implementation_crate_name:ident ::
```

**Comment by dtolnay** [comment]
Thanks, I would accept a PR to fix this.
