### ISSUE TITLE
Not working with no_std

### ISSUE THREAD

**Issue by tkaitchuck** [dtolnay/proc-macro-hack#38]
In lib.rs https://github.com/dtolnay/proc-macro-hack/blob/master/src/lib.rs#L516
it is doing a use on `std::iter::FromIterator;` this causes the complication to fail when std is not available. 
I've tested locally, and changing that lone to `use core::iter::FromIterator;` allows it to work just fine.

**Comment by dtolnay** [comment]
As in https://github.com/rust-lang/hashbrown/issues/109#issuecomment-518540789, I don't believe that this needs to be changed. I would prefer not to support proc macros where the macro implementation itself is no_std, because there should be no reason to write a proc macro that way.
