### ISSUE TITLE
Failing in nightly

### ISSUE THREAD

**Issue by zbraniecki** [dtolnay/proc-macro-hack#40]
This started failing in today's nightly with 
```
error: cannot find macro `proc_macro_call!` in this scope
```

See: https://travis-ci.org/dtolnay/proc-macro-hack/jobs/573050678

**Comment by dtolnay** [comment]
Macro resolution is currently broken in nightly -- https://github.com/rust-lang/rust/issues/63651. I would recommend using an older nightly for now. <kbd>nightly-2019-08-16</kbd> should work.

**Comment by dtolnay** [comment]
Fixed in nightly-2019-08-19.
