### ISSUE TITLE
Can't call macro defined as `#[proc_macro_hack(support_nested)]` from output of macro  defined as `#[proc_macro_hack(support_nested)]`

### ISSUE THREAD

**Issue by olegnn** [dtolnay/proc-macro-hack#41]
Consider having a macro exported as `#[proc_macro_hack(support_nested)]` which inserts macro defined as `#[proc_macro_hack(support_nested)]`. We will get following error:
```
error[E0659]: `proc_macro_call_0` is ambiguous (macro-expanded name vs less macro-expanded name from outer scope during import/macro resolution)
```
This situation may occur if we create an async macro using `#[proc_macro_hack(support_nested)]`, which internally uses `join!` or `select!` from https://github.com/rust-lang-nursery/futures-rs. 

I didn't find any possibility to import `join` function declared in https://github.com/rust-lang-nursery/futures-rs/tree/master/futures-join-macro directly in order to process token stream during code generation in custom macro. Appreciate any help.

**Comment by dtolnay** [comment]
Could you share a minimal snippet of code that I can compile to reproduce the same error?

**Comment by olegnn** [comment]
@dtolnay https://github.com/olegnn/proc_macro_hack_bug

**Comment by dtolnay** [comment]
Thanks! It looks like the call to futures::join generated by the macro is not visible to our existing workaround for nested macro calls which is based only on the macro's input tokens. I added a new workaround and opened https://github.com/olegnn/proc_macro_hack_bug/pull/1 with a fix.

**Comment by olegnn** [comment]
Thank you for the quick fix.
