### ISSUE TITLE
Eager macro expansion

### ISSUE THREAD

**Issue by alecmocatta** [dtolnay/proc-macro-hack#44]
This was asked back in 2017, https://github.com/dtolnay/proc-macro-hack/issues/3, but I wonder if things have change since? [This reddit thread](https://www.reddit.com/r/rust/comments/8wwwm5/eager_a_crate_for_eager_macro_expansion/) suggests perhaps it has?

Is it possible for the input to have macro invocations eagerly expanded?

**Comment by dtolnay** [comment]
No change since #3, as far as I know.
