### ISSUE TITLE
Looping through the Tokenstream and assigning syn::Idents looses information?

### ISSUE THREAD

**Issue by Jasperav** [dtolnay/proc-macro-hack#54]
I have a minimal reproduction project here: https://github.com/Jasperav/macro_cast. Running the test inside implcrate/src/main.rs fails). It shows that assigning `syn::Idents` by looping through the `TokenTree` looses/changes `Span` information. Say I have this function and a `proc-macro-hack` call:

```
fn expand_casts(column0: i32, column1: i32) {
    // Should expand to
    // ("some_text", column0 as i32, column1 as i32);
    add_casts!("some_text", column0, column1);
}
```

I want to expand the macro to: `("some_text", column0 as i32, column1 as i32);`.  This means: add some casts the local variables (they do not have to be the same type as the type parameter, just some type determined inside the macro which I omitted in this example).

I am currently looping throughout the `TokenTree`, searching for everything that comes after the first comma. Anything after the first comma should be a comma separated list of `syn::Ident` (local variables). This is somehow a problem in hygiene, since it gives me this error:

> cannot find value `column0` in this scope

Note: If the input of the macro is only `column0` (e.g.: `add_casts!(column0);`) and a direct cast from `TokenTree` to `syn::Ident` (e.g.: `let some_ident: syn::Ident = parse_macro_input!(input);`), I can expand the code succesfully (but I want more parameters and the first argument is a raw `&str`). 

This gives somehow a different output for the same call (e.g.: `add_cast_m!(i);`:

```
#[proc_macro_hack]
pub fn add_cast_m(input: TokenStream) -> TokenStream {
    let mut s: Option<syn::Ident> = None;

    for i in input.clone() {
        s = parse_quote!(i);
    }

    let s = s.unwrap();
    let y: syn::Ident = parse_macro_input!(input);
    // Why is s different than y?
    panic!("non-compiling one: {:#?}, compiling one: {:#?}", s, y);
}
```

Anyway, this is the relevant proc macro method which fails to expand (copy paste code from the linked repo): 

```
#[proc_macro_hack]
pub fn add_casts(input: TokenStream) -> TokenStream {
    let mut index = -1;
    let mut text = String::new();
    let mut idents: Vec<syn::Ident> = vec![];

    for i in input {
        index += 1;

        if index % 2 != 0 {
            // Each element should be separated by a comma
            match i {
                TokenTree::Punct(l) => assert_eq!(",", l.to_string()),
                _ => panic!("Expected punct, got {:#?}", i)
            }
            continue;
        }

        if index == 0 {
            // This is the text
            match i {
                TokenTree::Literal(l) => text = l.to_string(),
                _ => panic!("Expected literal, got {:#?}", i)
            }
        } else {
            match i {
                TokenTree::Ident(i) => idents.push(syn::parse_str(&i.to_string()).unwrap()),
                _ => panic!("Expected ident, got {:#?}", i)
            }
        }
    }

    let q = quote! {
        (#text, #(#idents as i32),*)
    };

    q.into()
}
```

**Comment by dtolnay** [comment]
You're throwing away the `Span`s on this line:

```rust
TokenTree::Ident(i) => idents.push(syn::parse_str(&i.to_string()).unwrap()),
```

On that line you convert from a proc_macro::Ident (with span information) to a plain String.

Generally you'll want to do all parsing using the parsing functionality in Syn to avoid this. https://docs.rs/syn/1/syn/parse/index.html

**Comment by Jasperav** [comment]
@dtolnay  I checked the provided link, but I don't see a method that can parse a `TokenTree`/`proc_macro::Ident` to a `syn::Ident`. I also tried `parse()` and `into()` on the `i` variable but that didn't work because the transformation is not implemented. 

Do you have a recommendation to parse a `proc_marco::Ident` to a `syn::Ident` without losing `Span` information?

**Comment by dtolnay** [comment]
Once you write the parsing logic using Syn, you would use https://docs.rs/syn/1/syn/parse/trait.Parser.html#method.parse to run it on the input proc_macro::TokenStream.

```rust
fn my_parser(input: ParseStream) -> Result<...> {
    ...
    // at the part where you want an ident:
    let ident: Ident = input.parse()?;
    ...
}


let result = my_parser.parse(input);
```
