### ISSUE TITLE
Compiling with lld rebuilds every time

### ISSUE THREAD

**Issue by Dispersia** [dtolnay/proc-macro-hack#56]
Hello, I have noticed when compiling other crates that compiling with lld causes this crate to compile every single time, even back to back runs with no changes (on a windows machine, latest nightly). I am unsure of how to diagnose this behavior, i tried to rip things out to find what was causing it but was unsuccessful. Have you seen/know how to figure this out?

**Comment by kabergstrom** [comment]
I am also experiencing this issue. lld is much faster for me so it'd be great if this could be fixed.

**Comment by dtolnay** [comment]
It is unusual that this would be linker-specific. Seems like this would be a cargo or rustc bug. This crate is just an ordinary proc macro crate with no dependencies; there would be no reason to rebuild it when nothing has changed. Someone should put together a minimal repro and report it in the appropriate place.

**Comment by rw** [comment]
I ran into this, too. Here's how I fixed it on my machine.

I realized that my rustup installation was out of sync: rustc was at 1.46.0-nightly and cargo was at 1.45.0-nightly. A regular rustup update did not fix the problem, nor did reinstalling the toolchain. I was able to fix the version mismatch problem by running `rustup toolchain install --force nightly`. Afterwards, both cargo and rustc reported a version of 1.46.0-nightly. proc-macro-hack started successfully being cached by cargo. YMMV but I hope this helps.

**Comment by Dispersia** [comment]
I just went to try it, force updating the toolchain did not fix it for me, however i then decided to `rustup update` and pulled latest lld and rebuilt that, and this no longer seems to occur for me either. I don't know which one fixed it, but for anyone that runs into this issue, try what @rw posted, and update rustup/lld. This makes working with lld much more bareable again, thank you for the comment!

**Comment by golddranks** [comment]
Just reporting in, that I also had this issue, and syncing `cargo` and `rustc` versions to `stable-1.46` helped.
