### ISSUE TITLE
Do I need to add 'use' for every file when I use a proc macro hack?

### ISSUE THREAD

**Issue by Jasperav** [dtolnay/proc-macro-hack#58]
This is a small reproduction project:  https://github.com/Jasperav/importprocmacro (try to run main and it gives a compile time error).
I have a proc macro, called `query`. To use it, I need to put this inside every file to make it work:

```
use proc_macro_hack::proc_macro_hack;
[proc_macro_hack]
use b_query::query;
```

I was wondering, is there a way I can 'global' import 'query' for all of my files? There is something like #[macro_use] but that didn't help me. I don't want the 'use'  everywhere in my code, just in my main.rs.

**Comment by dtolnay** [comment]
Fixed in 0.5.17.

**Comment by dtolnay** [comment]
Never mind, that ends up hitting "```macro-expanded `#[macro_use]`s may not shadow existing macros (see RFC 1560)```" in some cases so I've yanked it for now. A workaround is to add your own:

```rust
#[macro_use]
extern crate b_query as _;
```

in the crate root.

**Comment by Jasperav** [comment]
Thanks, the workaround is working!
