### ISSUE TITLE
Consider compiling to pass-through implementation on new compilers

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro-hack#62]
On Rust versions 1.45 and newer (https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html#stabilizing-function-like-procedural-macros-in-expressions-patterns-and-statements) we can bypass all of proc-macro-hack and expand as follows:

```rust
#[proc_macro_hack]
pub use mymacro_impl::mymacro;

// expands to:
pub use mymacro_impl::mymacro;
```

```rust
#[proc_macro_hack]
pub fn mymacro(input: TokenStream) -> TokenStream {...}

// expands to:
#[proc_macro]
pub fn mymacro(input: TokenStream) -> TokenStream {...}
```

This will improve macro expansion performance for libraries that need to support a range of compiler versions including ones older than 1.45.

**Comment by Artoria2e5** [comment]
@Icenowy reports another use case: this crate somehow breaks LTO interop with Clang (missing symbol), but the new rust macro doesn't.

**Comment by taiki-e** [comment]
Filed #64
